name: Java CI

on: 
  push:
    paths:
      - 'timer/*'

defaults:
  run:
    shell: bash
    working-directory: timer

jobs:
  test:
    name: Build & Unit Tests
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.4
      - name: Compile
        run: mvn -B clean compile
      - name: Build
        run: mvn -B clean verify
      - name: Package
        run: mvn -B clean package -DskipTests

  artifact:
    name: Publish - GitHub Packages
    runs-on: ubuntu-18.04
    needs: [test]

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.4
      - name: Publish artifact on GitHub Packages
        run: mvn -B clean deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
